app:
  name: springbott-mongo-demo
  description: This projects demonstrats how how run Spring Boot, Mongo DB

logging:
  file: app.log

server:
  port: 8080

spring.thymeleaf.cache: false
spring.thymeleaf.mode: LEGACYHTML5

#spring.data.mongodb.uri: mongodb://idgst-mongo:27017/digest